-- MySQL Script generated by MySQL Workbench
-- 05/31/15 17:09:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema achadoseperdidos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema achadoseperdidos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `achadoseperdidos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `achadoseperdidos` ;

-- -----------------------------------------------------
-- Table `achadoseperdidos`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `achadoseperdidos`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `telefone` INT NULL,
  `tipo` INT NULL,
  PRIMARY KEY (`idperfil`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `idperfil_UNIQUE` (`idperfil` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `achadoseperdidos`.`objeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `achadoseperdidos`.`objeto` (
  `idobjeto` INT NOT NULL AUTO_INCREMENT,
  `identificacao` VARCHAR(45) NULL,
  `descricao` TEXT(200) NULL,
  `data` DATE NULL,
  `foto` VARCHAR(100) NULL,
  `status` INT NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`idobjeto`),
  INDEX `fk_objeto_perfil_idx` (`perfil_idperfil` ASC),
  UNIQUE INDEX `idobjeto_UNIQUE` (`idobjeto` ASC),
  CONSTRAINT `fk_objeto_perfil`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `achadoseperdidos`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `achadoseperdidos`.`requisicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `achadoseperdidos`.`requisicao` (
  `idrequisicao` INT NOT NULL AUTO_INCREMENT,
  `perfil_idperfil` INT NOT NULL,
  `objeto_idobjeto` INT NOT NULL,
  PRIMARY KEY (`idrequisicao`),
  INDEX `fk_requisicao_perfil1_idx` (`perfil_idperfil` ASC),
  UNIQUE INDEX `idrequisicao_UNIQUE` (`idrequisicao` ASC),
  INDEX `fk_requisicao_objeto1_idx` (`objeto_idobjeto` ASC),
  CONSTRAINT `fk_requisicao_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `achadoseperdidos`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requisicao_objeto1`
    FOREIGN KEY (`objeto_idobjeto`)
    REFERENCES `achadoseperdidos`.`objeto` (`idobjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
